### ISSUE TITLE
convert vmodtool-rs.py into macros

### ISSUE THREAD

**Issue by gquintard** [gquintard/varnish-rs#2]

**Comment by dhamidi** [comment]
I tried looking into this over the weekend, expecting that it's rather straightforward but then realized that `vmodtool-rs` is importing the `vmodtool` that comes with Varnish.

This makes me wonder:

:one: is it actually worth it to replace `vmodtool-rs`?  Unless Varnish itself stops relying on vmodtool, we'll always have python3 and vmodtool available in the development environment.
:two: to properly replace `vmodtool-rs` with a procmacro would mean re-implementing a full vcc parser in Rust.  Shouldn't that be a separate binary then, rather than a procmacro, so that it can eventually be merged back into Varnish?

Writing a parser for `vcc` files in Rust sure sounds like fun, I'm just wondering whether that's the right direction.

**Comment by gquintard** [comment]
yeah, this issue is more "maybe we can explore that" than "we should do it", and more than the parser, it's the generation of JSON that annoys me, as the varnish parser is super picky, so it will be a chore.

It would be nice to have cleaner code though, even if we stay in the `python` realm. The current implementation isn't pretty :-)

**Comment by nyurik** [comment]
done :)
